[tool.black]
line-length = 80
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | bin
  | build
  | dist
  | __pycache__
  | docs
  | venv
)/
'''

[tool.isort]
combine_star = true
ensure_newline_before_comments = true
float_to_top = true
include_trailing_comma = true
line_length = 80
multi_line_output= 3
skip = ["venv"]
src_paths = ["app"]
known_tests = ['tests']
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'TESTS', 'FIRSTPARTY', 'LOCALFOLDER']
use_parentheses = true
