[tool.black]
line-length = 80
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | bin
  | build
  | dist
  | __pycache__
  | docs
  | venv
)/
'''

[tool.ruff]
target-version = 'py310'
line-length = 80
exclude = [
    '.git',
    '__pycache__',
    'docs',
    'venv'
]

[tool.ruff.lint]
select = [
    'E',  # pycodestyle errors
    'W',  # pycodestyle warnings
    'F',  # pyflakes
    'C',  # flake8-comprehensions
    'B',  # flake8-bugbear
    'I',  # isort
]
ignore = [
    'E501',  # line too long, handled by black
    'B008',  # do not perform function calls in argument defaults
]

[tool.ruff.lint.isort]
known-local-folder = ['app']
combine-as-imports = true

[tool.ruff.lint.mccabe]
max-complexity = 17
